language: ruby
secure: "fX7q1GzICgUgdNygM5vn20bbShhRFfS7Re33vzNUI3a84ZV0Gt/avKOWqPyY2GNq69bLnHStprjMNHwjwOQ6ww0hnWd12VMU/RrRzUhCrKc+zOODy7B/USc8fRxmhsgs+qqtru+j4SF+sE4+kmP4+a8tm+eynB/I+Yi/cux4h9BqVago3HIcFj5+374FWSqWqygf1pyhXEd3sbyJ24t8EEmtZ7qoAWaV6PJaICxjfAKMD8oSU+OO7ccT9Gqj/6HSNx5bJTdLrT68akPad3qPf9mCkttiDPFaznA64RrYSH4YYQBCNzGvPqyPKCl+OSVIA+IZc/+4pcw6Sgnk32MX0062QcsLeewCRKxGXbrEX+Ak6GYbVNOXtpg06fpuljb5oFa7j51PkZjvqnHY7PoUM3cVmOW8TNi0dLZoavBfeGRkXpy/8RvMhgSiuhqObaOl+cNdE+gkh+p3gkAYrl5bc3gpZBhCtAuSVKam0iWeDXwMmm8Xa0W4vaMbYV95EUDnLm5JK/ObxK6JjK6L4wMYgV94v+Wt/UfNPNhxTkxM+6RCoM4OTL9HgpO0NLQjrq/9DzzHtWv3N7f+NkOYCBoMDn5/lxliu3pFOXT0TRWE+CfFSkyduX7wcyyeNw77Jm8eb1JlPLEmvPZYAHtEaaCHjhWzx1yydeUE11MZEPyaHU0="
rvm:
- 2.2
script:
- bundle exec jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_b635d6f2115a_key -iv $encrypted_b635d6f2115a_iv
  -in travis.id_rsa.enc -out travis.id_rsa -d
deploy:
- tar -caf .site.tar.gz _site
- scp -i travis.id_rsa .site.tar.gz $(USER)@$(HOST):
- ssh -t $USER@$(HOST) "rm -rf _site && tar -xaf .site.tar.gz && cd _site && sudo /data/www/deploy_rustycrate.sh"
after_deploy:
- shred -u travis.id_rsa
