language: ruby
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: csl2OVpn0L49E+L/rRMSR0Iq6Qb/1oEpoRaQFehJE7RiZXeAVHrILINLq+4HN2JrqOjeg8cBunKzUhp0sHBxly0M36NsJN8ITZVKbNENzwcenVfNlJPgxVomBUWmWk4w96w5eFRfxVLR5UDN6Rf7ohkQMxYjd2KWL9iugzIb8+Epq7akSyM0XCXeJpL9T6Z+WDWrX3xeiLgTUfdofik5GAyEcLLjz1ncdCwvBrnj4s1//tb35ex+6MDNr3bO9KD0rpuwIPzFYGwZcYchK8TfqFB/3fseUHVzb6/Q0V9K8meOwfKxU8Rd9o0CS6Z02rizz6zjnu5TcMFR65HOlVsQ1SzDIb7I7Me6jnDYrPhhJulu9x1jxNALHWO0cF/phMldoj6KyZ3qZ/NVv8R/6Ukj7S3B4IgzPSO7/Z5QWDkv72L3CKheof8tmSC5SGv6mShxCqQqIbajRbc/yeWP8HNNsEjUUjnf5/DK3s458LeCHh0472KJKgo0eLea2LD8sd16Xx0IK1WYFgv+WUUnI3MhERPxepL4ugFlGmHAwA/V/smmRRMnqKYMTAw//4ceZO9ylRzuyWzWmWbRzExHgK6jVZqxtjp2UKG6L39n1LFDbQErw3TrJdBso9ZKKWjUff/tyDBglkgw05OGYgc8TpQW3AHWs7t/O1JBXzP94bMPVkw=
addons:
  ssh_known_hosts: rustycrate.ru
sudo: false
rvm:
- 2.2
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html
after_success:
- if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
  openssl aes-256-cbc -K $encrypted_b635d6f2115a_key -iv $encrypted_b635d6f2115a_iv
    -in travis.trash.id_rsa.enc -out travis.trash.id_rsa -d;
  tar -caf .site.tar.gz _site;
  chmod 600 travis.trash.id_rsa;
  scp -i travis.trash.id_rsa .site.tar.gz "$USER@$HOST:";
  ssh -i travis.trash.id_rsa -t $USER@$HOST "rm -rf _site && tar -xaf .site.tar.gz
    && cd _site && sudo /data/www/deploy_rustycrate.sh";
  fi;
after_script:
- if [ -f travis.trash.id_rsa ]; then shred -u travis.trash.id_rsa; fi;
notifications:
  slack:
    secure: f2tvffqlKcJL+f2BAT7+1n5KmUfPk8nJW73DXPOce/MO18KL5Ftyjg4Kx2wyycxlj1/c+w3KeqIOYw2QPiFkVUqc/klKWeEUM9efDzv5zjibaUgEWuSaN62sdckkVqvG/IMGTGK92LT3XphjVy6YFNqSurwq8Wp0w+9n1h4wRQ6EWavD2QfZ1WalxWRyYV3wQOX6QsgWaAAfDaJS7PyK9Gp09MIqHsTpQDssp13qxFTc3pfvoVp8lBSn0OTZR68IA2Nehk5gbS7DK3U+++228Kq60k8ie/u7dgnV7BbI0BtCqSAejoTL5jC5FMzGUbLwclGyF8VJKzxjl5TDB88XUKwcC7+4Ilni77j5scCqzLcA3dORMTa/hPIN7FC/kx44HNjDLxmNkQJWzHyYse+DXDDN4qM/+Wcp8QasJ9LAh8Pnzm0fMJd82/c8GqgAWz1H2SyCIh/3+hZwzK2Fc0S5jBCUN7i4kEZdamvdlcJYzWSqOxpwj5df34SVNYKyn/egV4V++dbOGOVWDYLUu67m87UL6dUXKAED3JdD2PjrOzWDMzfQCutzSAZf+jOXtKeO0BOppnL9IRcK+k0C84+g/ydtjzIXZ8LaORAt5dNUcy4HMQMiRkeqo9fQ8MTUCk4N0mr0N4oC7Y8VS3xiles68ItiAWtf0jbqXoOYNmNw7tc=
